-- Seed Card Kingdom Edition names mapped from real data
BEGIN;
UPDATE tcg_set SET ck_name = 'Secrets of Strixhaven Mystical Archive' WHERE tcg = 'mtg' AND code = 'soa';
UPDATE tcg_set SET ck_name = 'Secrets of Strixhaven' WHERE tcg = 'mtg' AND code = 'sos';
UPDATE tcg_set SET ck_name = 'Teenage Mutant Ninja Turtles' WHERE tcg = 'mtg' AND code = 'tmt';
UPDATE tcg_set SET ck_name = 'Lorwyn Eclipsed' WHERE tcg = 'mtg' AND code = 'ecl';
UPDATE tcg_set SET ck_name = 'Avatar: The Last Airbender' WHERE tcg = 'mtg' AND code = 'tla';
UPDATE tcg_set SET ck_name = 'Marvel''s Spider-Man' WHERE tcg = 'mtg' AND code = 'spm';
UPDATE tcg_set SET ck_name = 'Edge of Eternities' WHERE tcg = 'mtg' AND code = 'eoe';
UPDATE tcg_set SET ck_name = 'Final Fantasy' WHERE tcg = 'mtg' AND code = 'fin';
UPDATE tcg_set SET ck_name = 'Tarkir: Dragonstorm' WHERE tcg = 'mtg' AND code = 'tdm';
UPDATE tcg_set SET ck_name = 'Aetherdrift' WHERE tcg = 'mtg' AND code = 'dft';
UPDATE tcg_set SET ck_name = 'Innistrad Remastered' WHERE tcg = 'mtg' AND code = 'inr';
UPDATE tcg_set SET ck_name = 'Foundations' WHERE tcg = 'mtg' AND code = 'fdn';
UPDATE tcg_set SET ck_name = 'Foundations Jumpstart' WHERE tcg = 'mtg' AND code = 'j25';
UPDATE tcg_set SET ck_name = 'Foundations Commander' WHERE tcg = 'mtg' AND code = 'fdc';
UPDATE tcg_set SET ck_name = 'Duskmourn: House of Horror' WHERE tcg = 'mtg' AND code = 'dsk';
UPDATE tcg_set SET ck_name = 'Mystery Booster 2' WHERE tcg = 'mtg' AND code = 'mb2';
UPDATE tcg_set SET ck_name = 'Bloomburrow' WHERE tcg = 'mtg' AND code = 'blb';
UPDATE tcg_set SET ck_name = 'Modern Horizons 3' WHERE tcg = 'mtg' AND code = 'mh3';
UPDATE tcg_set SET ck_name = 'Outlaws of Thunder Junction' WHERE tcg = 'mtg' AND code = 'otj';
UPDATE tcg_set SET ck_name = 'Ravnica: Clue Edition' WHERE tcg = 'mtg' AND code = 'clu';
UPDATE tcg_set SET ck_name = 'Murders at Karlov Manor' WHERE tcg = 'mtg' AND code = 'mkm';
UPDATE tcg_set SET ck_name = 'Ravnica Remastered' WHERE tcg = 'mtg' AND code = 'rvr';
UPDATE tcg_set SET ck_name = 'Special Guests' WHERE tcg = 'mtg' AND code = 'spg';
UPDATE tcg_set SET ck_name = 'The Lost Caverns of Ixalan' WHERE tcg = 'mtg' AND code = 'lci';
UPDATE tcg_set SET ck_name = 'Wilds of Eldraine' WHERE tcg = 'mtg' AND code = 'woe';
UPDATE tcg_set SET ck_name = 'Commander Masters' WHERE tcg = 'mtg' AND code = 'cmm';
UPDATE tcg_set SET ck_name = 'The Lord of the Rings: Tales of Middle-earth' WHERE tcg = 'mtg' AND code = 'ltr';
UPDATE tcg_set SET ck_name = 'March of the Machine: The Aftermath' WHERE tcg = 'mtg' AND code = 'mat';
UPDATE tcg_set SET ck_name = 'Multiverse Legends' WHERE tcg = 'mtg' AND code = 'mul';
UPDATE tcg_set SET ck_name = 'March of the Machine' WHERE tcg = 'mtg' AND code = 'mom';
UPDATE tcg_set SET ck_name = 'Phyrexia: All Will Be One' WHERE tcg = 'mtg' AND code = 'one';
UPDATE tcg_set SET ck_name = 'Dominaria Remastered' WHERE tcg = 'mtg' AND code = 'dmr';
UPDATE tcg_set SET ck_name = 'Starter Commander Decks' WHERE tcg = 'mtg' AND code = 'scd';
UPDATE tcg_set SET ck_name = 'Jumpstart 2022' WHERE tcg = 'mtg' AND code = 'j22';
UPDATE tcg_set SET ck_name = 'The Brothers'' War Retro Artifacts' WHERE tcg = 'mtg' AND code = 'brr';
UPDATE tcg_set SET ck_name = 'The Brothers'' War' WHERE tcg = 'mtg' AND code = 'bro';
UPDATE tcg_set SET ck_name = 'Game Night: Free-for-All' WHERE tcg = 'mtg' AND code = 'gn3';
UPDATE tcg_set SET ck_name = 'Unfinity' WHERE tcg = 'mtg' AND code = 'unf';
UPDATE tcg_set SET ck_name = 'Dominaria United' WHERE tcg = 'mtg' AND code = 'dmu';
UPDATE tcg_set SET ck_name = 'Double Masters 2022' WHERE tcg = 'mtg' AND code = '2x2';
UPDATE tcg_set SET ck_name = 'Commander Legends: Battle for Baldur''s Gate' WHERE tcg = 'mtg' AND code = 'clb';
UPDATE tcg_set SET ck_name = 'Streets of New Capenna' WHERE tcg = 'mtg' AND code = 'snc';
UPDATE tcg_set SET ck_name = 'Kamigawa: Neon Dynasty' WHERE tcg = 'mtg' AND code = 'neo';
UPDATE tcg_set SET ck_name = 'Commander Collection: Black' WHERE tcg = 'mtg' AND code = 'cc2';
UPDATE tcg_set SET ck_name = 'Innistrad: Double Feature' WHERE tcg = 'mtg' AND code = 'dbl';
UPDATE tcg_set SET ck_name = 'Innistrad: Crimson Vow' WHERE tcg = 'mtg' AND code = 'vow';
UPDATE tcg_set SET ck_name = 'Innistrad: Midnight Hunt' WHERE tcg = 'mtg' AND code = 'mid';
UPDATE tcg_set SET ck_name = 'Adventures in the Forgotten Realms' WHERE tcg = 'mtg' AND code = 'afr';
UPDATE tcg_set SET ck_name = 'Modern Horizons 2' WHERE tcg = 'mtg' AND code = 'mh2';
UPDATE tcg_set SET ck_name = 'Commander 2021' WHERE tcg = 'mtg' AND code = 'c21';
UPDATE tcg_set SET ck_name = 'Strixhaven: School of Mages' WHERE tcg = 'mtg' AND code = 'stx';
UPDATE tcg_set SET ck_name = 'Strixhaven Mystical Archive' WHERE tcg = 'mtg' AND code = 'sta';
UPDATE tcg_set SET ck_name = 'Time Spiral Remastered' WHERE tcg = 'mtg' AND code = 'tsr';
UPDATE tcg_set SET ck_name = 'Kaldheim' WHERE tcg = 'mtg' AND code = 'khm';
UPDATE tcg_set SET ck_name = 'Commander Collection: Green' WHERE tcg = 'mtg' AND code = 'cc1';
UPDATE tcg_set SET ck_name = 'Commander Legends' WHERE tcg = 'mtg' AND code = 'cmr';
UPDATE tcg_set SET ck_name = 'Zendikar Rising Expeditions' WHERE tcg = 'mtg' AND code = 'zne';
UPDATE tcg_set SET ck_name = 'Zendikar Rising' WHERE tcg = 'mtg' AND code = 'znr';
UPDATE tcg_set SET ck_name = 'Double Masters' WHERE tcg = 'mtg' AND code = '2xm';
UPDATE tcg_set SET ck_name = 'Jumpstart' WHERE tcg = 'mtg' AND code = 'jmp';
UPDATE tcg_set SET ck_name = 'Core Set 2021' WHERE tcg = 'mtg' AND code = 'm21';
UPDATE tcg_set SET ck_name = 'Signature Spellbook: Chandra' WHERE tcg = 'mtg' AND code = 'ss3';
UPDATE tcg_set SET ck_name = 'Ikoria: Lair of Behemoths' WHERE tcg = 'mtg' AND code = 'iko';
UPDATE tcg_set SET ck_name = 'Commander 2020' WHERE tcg = 'mtg' AND code = 'c20';
UPDATE tcg_set SET ck_name = 'Unsanctioned' WHERE tcg = 'mtg' AND code = 'und';
UPDATE tcg_set SET ck_name = 'Theros Beyond Death' WHERE tcg = 'mtg' AND code = 'thb';
UPDATE tcg_set SET ck_name = 'Game Night 2019' WHERE tcg = 'mtg' AND code = 'gn2';
UPDATE tcg_set SET ck_name = 'Throne of Eldraine' WHERE tcg = 'mtg' AND code = 'eld';
UPDATE tcg_set SET ck_name = 'Commander 2019' WHERE tcg = 'mtg' AND code = 'c19';
UPDATE tcg_set SET ck_name = 'Core Set 2020' WHERE tcg = 'mtg' AND code = 'm20';
UPDATE tcg_set SET ck_name = 'Signature Spellbook: Gideon' WHERE tcg = 'mtg' AND code = 'ss2';
UPDATE tcg_set SET ck_name = 'Modern Horizons' WHERE tcg = 'mtg' AND code = 'mh1';
UPDATE tcg_set SET ck_name = 'War of the Spark' WHERE tcg = 'mtg' AND code = 'war';
UPDATE tcg_set SET ck_name = 'Ravnica Allegiance' WHERE tcg = 'mtg' AND code = 'rna';
UPDATE tcg_set SET ck_name = 'Ultimate Box Topper' WHERE tcg = 'mtg' AND code = 'puma';
UPDATE tcg_set SET ck_name = 'Ultimate Masters' WHERE tcg = 'mtg' AND code = 'uma';
UPDATE tcg_set SET ck_name = 'Game Night' WHERE tcg = 'mtg' AND code = 'gnt';
UPDATE tcg_set SET ck_name = 'Guilds of Ravnica' WHERE tcg = 'mtg' AND code = 'grn';
UPDATE tcg_set SET ck_name = 'Commander 2018' WHERE tcg = 'mtg' AND code = 'c18';
UPDATE tcg_set SET ck_name = 'Core Set 2019' WHERE tcg = 'mtg' AND code = 'm19';
UPDATE tcg_set SET ck_name = 'Signature Spellbook: Jace' WHERE tcg = 'mtg' AND code = 'ss1';
UPDATE tcg_set SET ck_name = 'Battlebond' WHERE tcg = 'mtg' AND code = 'bbd';
UPDATE tcg_set SET ck_name = 'Dominaria' WHERE tcg = 'mtg' AND code = 'dom';
UPDATE tcg_set SET ck_name = 'Duel Decks: Elves Vs. Inventors' WHERE tcg = 'mtg' AND code = 'ddu';
UPDATE tcg_set SET ck_name = 'Masters 25' WHERE tcg = 'mtg' AND code = 'a25';
UPDATE tcg_set SET ck_name = 'Rivals of Ixalan' WHERE tcg = 'mtg' AND code = 'rix';
UPDATE tcg_set SET ck_name = 'Unstable' WHERE tcg = 'mtg' AND code = 'ust';
UPDATE tcg_set SET ck_name = 'Explorers of Ixalan' WHERE tcg = 'mtg' AND code = 'e02';
UPDATE tcg_set SET ck_name = 'From the Vault: Transform' WHERE tcg = 'mtg' AND code = 'v17';
UPDATE tcg_set SET ck_name = 'Iconic Masters' WHERE tcg = 'mtg' AND code = 'ima';
UPDATE tcg_set SET ck_name = 'Duel Decks: Merfolk vs. Goblins' WHERE tcg = 'mtg' AND code = 'ddt';
UPDATE tcg_set SET ck_name = 'Ixalan' WHERE tcg = 'mtg' AND code = 'xln';
UPDATE tcg_set SET ck_name = 'Commander 2017' WHERE tcg = 'mtg' AND code = 'c17';
UPDATE tcg_set SET ck_name = 'Hour of Devastation' WHERE tcg = 'mtg' AND code = 'hou';
UPDATE tcg_set SET ck_name = 'Commander Anthology' WHERE tcg = 'mtg' AND code = 'cma';
UPDATE tcg_set SET ck_name = 'Amonkhet' WHERE tcg = 'mtg' AND code = 'akh';
UPDATE tcg_set SET ck_name = 'Duel Decks: Mind Vs. Might' WHERE tcg = 'mtg' AND code = 'dds';
UPDATE tcg_set SET ck_name = 'Modern Masters 2017' WHERE tcg = 'mtg' AND code = 'mm3';
UPDATE tcg_set SET ck_name = 'Aether Revolt' WHERE tcg = 'mtg' AND code = 'aer';
UPDATE tcg_set SET ck_name = 'Planechase Anthology' WHERE tcg = 'mtg' AND code = 'pca';
UPDATE tcg_set SET ck_name = 'Commander 2016' WHERE tcg = 'mtg' AND code = 'c16';
UPDATE tcg_set SET ck_name = 'Kaladesh' WHERE tcg = 'mtg' AND code = 'kld';
UPDATE tcg_set SET ck_name = 'Duel Decks: Nissa Vs. Ob Nixilis' WHERE tcg = 'mtg' AND code = 'ddr';
UPDATE tcg_set SET ck_name = 'From the Vault: Lore' WHERE tcg = 'mtg' AND code = 'v16';
UPDATE tcg_set SET ck_name = 'Eldritch Moon' WHERE tcg = 'mtg' AND code = 'emn';
UPDATE tcg_set SET ck_name = 'Eternal Masters' WHERE tcg = 'mtg' AND code = 'ema';
UPDATE tcg_set SET ck_name = 'Shadows Over Innistrad' WHERE tcg = 'mtg' AND code = 'soi';
UPDATE tcg_set SET ck_name = 'Duel Decks: Blessed Vs. Cursed' WHERE tcg = 'mtg' AND code = 'ddq';
UPDATE tcg_set SET ck_name = 'Oath of the Gatewatch' WHERE tcg = 'mtg' AND code = 'ogw';
UPDATE tcg_set SET ck_name = 'Commander 2015' WHERE tcg = 'mtg' AND code = 'c15';
UPDATE tcg_set SET ck_name = 'Battle for Zendikar' WHERE tcg = 'mtg' AND code = 'bfz';
UPDATE tcg_set SET ck_name = 'Duel Decks: Zendikar Vs. Eldrazi' WHERE tcg = 'mtg' AND code = 'ddp';
UPDATE tcg_set SET ck_name = 'From the Vault: Angels' WHERE tcg = 'mtg' AND code = 'v15';
UPDATE tcg_set SET ck_name = 'Magic Origins' WHERE tcg = 'mtg' AND code = 'ori';
UPDATE tcg_set SET ck_name = 'Modern Masters 2015' WHERE tcg = 'mtg' AND code = 'mm2';
UPDATE tcg_set SET ck_name = 'Dragons of Tarkir' WHERE tcg = 'mtg' AND code = 'dtk';
UPDATE tcg_set SET ck_name = 'Duel Decks: Elspeth Vs. Kiora' WHERE tcg = 'mtg' AND code = 'ddo';
UPDATE tcg_set SET ck_name = 'Fate Reforged' WHERE tcg = 'mtg' AND code = 'frf';
UPDATE tcg_set SET ck_name = 'Commander 2014' WHERE tcg = 'mtg' AND code = 'c14';
UPDATE tcg_set SET ck_name = 'Khans of Tarkir' WHERE tcg = 'mtg' AND code = 'ktk';
UPDATE tcg_set SET ck_name = 'Duel Decks: Speed Vs. Cunning' WHERE tcg = 'mtg' AND code = 'ddn';
UPDATE tcg_set SET ck_name = 'From the Vault: Annihilation' WHERE tcg = 'mtg' AND code = 'v14';
UPDATE tcg_set SET ck_name = 'Conspiracy' WHERE tcg = 'mtg' AND code = 'cns';
UPDATE tcg_set SET ck_name = 'Journey into Nyx' WHERE tcg = 'mtg' AND code = 'jou';
UPDATE tcg_set SET ck_name = 'Duel Decks: Jace Vs. Vraska' WHERE tcg = 'mtg' AND code = 'ddm';
UPDATE tcg_set SET ck_name = 'Born of the Gods' WHERE tcg = 'mtg' AND code = 'bng';
UPDATE tcg_set SET ck_name = 'Commander 2013' WHERE tcg = 'mtg' AND code = 'c13';
UPDATE tcg_set SET ck_name = 'Theros' WHERE tcg = 'mtg' AND code = 'ths';
UPDATE tcg_set SET ck_name = 'Duel Decks: Heroes Vs. Monsters' WHERE tcg = 'mtg' AND code = 'ddl';
UPDATE tcg_set SET ck_name = 'From the Vault: Twenty' WHERE tcg = 'mtg' AND code = 'v13';
UPDATE tcg_set SET ck_name = 'Modern Masters' WHERE tcg = 'mtg' AND code = 'mma';
UPDATE tcg_set SET ck_name = 'Dragon''s Maze' WHERE tcg = 'mtg' AND code = 'dgm';
UPDATE tcg_set SET ck_name = 'Duel Decks: Sorin Vs. Tibalt' WHERE tcg = 'mtg' AND code = 'ddk';
UPDATE tcg_set SET ck_name = 'Gatecrash' WHERE tcg = 'mtg' AND code = 'gtc';
UPDATE tcg_set SET ck_name = 'Commander''s Arsenal' WHERE tcg = 'mtg' AND code = 'cm1';
UPDATE tcg_set SET ck_name = 'Return to Ravnica' WHERE tcg = 'mtg' AND code = 'rtr';
UPDATE tcg_set SET ck_name = 'Duel Decks: Izzet Vs. Golgari' WHERE tcg = 'mtg' AND code = 'ddj';
UPDATE tcg_set SET ck_name = 'From the Vault: Realms' WHERE tcg = 'mtg' AND code = 'v12';
UPDATE tcg_set SET ck_name = 'Planechase 2012' WHERE tcg = 'mtg' AND code = 'pc2';
UPDATE tcg_set SET ck_name = 'Avacyn Restored' WHERE tcg = 'mtg' AND code = 'avr';
UPDATE tcg_set SET ck_name = 'Duel Decks: Venser Vs. Koth' WHERE tcg = 'mtg' AND code = 'ddi';
UPDATE tcg_set SET ck_name = 'Dark Ascension' WHERE tcg = 'mtg' AND code = 'dka';
UPDATE tcg_set SET ck_name = 'Premium Deck Series: Graveborn' WHERE tcg = 'mtg' AND code = 'pd3';
UPDATE tcg_set SET ck_name = 'Innistrad' WHERE tcg = 'mtg' AND code = 'isd';
UPDATE tcg_set SET ck_name = 'Duel Decks: Ajani Vs. Nicol Bolas' WHERE tcg = 'mtg' AND code = 'ddh';
UPDATE tcg_set SET ck_name = 'From the Vault: Legends' WHERE tcg = 'mtg' AND code = 'v11';
UPDATE tcg_set SET ck_name = 'New Phyrexia' WHERE tcg = 'mtg' AND code = 'nph';
UPDATE tcg_set SET ck_name = 'Duel Decks: Knights Vs. Dragons' WHERE tcg = 'mtg' AND code = 'ddg';
UPDATE tcg_set SET ck_name = 'Mirrodin Besieged' WHERE tcg = 'mtg' AND code = 'mbs';
UPDATE tcg_set SET ck_name = 'Scars of Mirrodin' WHERE tcg = 'mtg' AND code = 'som';
UPDATE tcg_set SET ck_name = 'Duel Decks: Elspeth Vs. Tezzeret' WHERE tcg = 'mtg' AND code = 'ddf';
UPDATE tcg_set SET ck_name = 'From the Vault: Relics' WHERE tcg = 'mtg' AND code = 'v10';
UPDATE tcg_set SET ck_name = 'Archenemy' WHERE tcg = 'mtg' AND code = 'arc';
UPDATE tcg_set SET ck_name = 'Duels of the Planeswalkers' WHERE tcg = 'mtg' AND code = 'dpa';
UPDATE tcg_set SET ck_name = 'Rise of the Eldrazi' WHERE tcg = 'mtg' AND code = 'roe';
UPDATE tcg_set SET ck_name = 'Duel Decks: Phyrexia Vs. The Coalition' WHERE tcg = 'mtg' AND code = 'dde';
UPDATE tcg_set SET ck_name = 'Worldwake' WHERE tcg = 'mtg' AND code = 'wwk';
UPDATE tcg_set SET ck_name = 'Premium Deck Series: Slivers' WHERE tcg = 'mtg' AND code = 'h09';
UPDATE tcg_set SET ck_name = 'Duel Decks: Garruk Vs. Liliana' WHERE tcg = 'mtg' AND code = 'ddd';
UPDATE tcg_set SET ck_name = 'Zendikar' WHERE tcg = 'mtg' AND code = 'zen';
UPDATE tcg_set SET ck_name = 'Planechase' WHERE tcg = 'mtg' AND code = 'hop';
UPDATE tcg_set SET ck_name = 'From the Vault: Exiled' WHERE tcg = 'mtg' AND code = 'v09';
UPDATE tcg_set SET ck_name = 'Alara Reborn' WHERE tcg = 'mtg' AND code = 'arb';
UPDATE tcg_set SET ck_name = 'Duel Decks: Divine Vs. Demonic' WHERE tcg = 'mtg' AND code = 'ddc';
UPDATE tcg_set SET ck_name = 'Conflux' WHERE tcg = 'mtg' AND code = 'con';
UPDATE tcg_set SET ck_name = 'Duel Decks: Jace Vs. Chandra' WHERE tcg = 'mtg' AND code = 'dd2';
UPDATE tcg_set SET ck_name = 'Shards of Alara' WHERE tcg = 'mtg' AND code = 'ala';
UPDATE tcg_set SET ck_name = 'From the Vault: Dragons' WHERE tcg = 'mtg' AND code = 'drb';
UPDATE tcg_set SET ck_name = 'Eventide' WHERE tcg = 'mtg' AND code = 'eve';
UPDATE tcg_set SET ck_name = 'Shadowmoor' WHERE tcg = 'mtg' AND code = 'shm';
UPDATE tcg_set SET ck_name = 'Morningtide' WHERE tcg = 'mtg' AND code = 'mor';
UPDATE tcg_set SET ck_name = 'Duel Decks: Elves Vs. Goblins' WHERE tcg = 'mtg' AND code = 'dd1';
UPDATE tcg_set SET ck_name = 'Lorwyn' WHERE tcg = 'mtg' AND code = 'lrw';
UPDATE tcg_set SET ck_name = '10th Edition' WHERE tcg = 'mtg' AND code = '10e';
UPDATE tcg_set SET ck_name = 'Future Sight' WHERE tcg = 'mtg' AND code = 'fut';
UPDATE tcg_set SET ck_name = 'Planar Chaos' WHERE tcg = 'mtg' AND code = 'plc';
UPDATE tcg_set SET ck_name = 'Time Spiral' WHERE tcg = 'mtg' AND code = 'tsp';
UPDATE tcg_set SET ck_name = 'Coldsnap' WHERE tcg = 'mtg' AND code = 'csp';
UPDATE tcg_set SET ck_name = 'Coldsnap Theme Decks' WHERE tcg = 'mtg' AND code = 'cst';
UPDATE tcg_set SET ck_name = 'Dissension' WHERE tcg = 'mtg' AND code = 'dis';
UPDATE tcg_set SET ck_name = 'Guildpact' WHERE tcg = 'mtg' AND code = 'gpt';
UPDATE tcg_set SET ck_name = '9th Edition' WHERE tcg = 'mtg' AND code = '9ed';
UPDATE tcg_set SET ck_name = 'Saviors of Kamigawa' WHERE tcg = 'mtg' AND code = 'sok';
UPDATE tcg_set SET ck_name = 'Betrayers of Kamigawa' WHERE tcg = 'mtg' AND code = 'bok';
UPDATE tcg_set SET ck_name = 'Unhinged' WHERE tcg = 'mtg' AND code = 'unh';
UPDATE tcg_set SET ck_name = 'Champions of Kamigawa' WHERE tcg = 'mtg' AND code = 'chk';
UPDATE tcg_set SET ck_name = 'Fifth Dawn' WHERE tcg = 'mtg' AND code = '5dn';
UPDATE tcg_set SET ck_name = 'Darksteel' WHERE tcg = 'mtg' AND code = 'dst';
UPDATE tcg_set SET ck_name = 'Mirrodin' WHERE tcg = 'mtg' AND code = 'mrd';
UPDATE tcg_set SET ck_name = '8th Edition' WHERE tcg = 'mtg' AND code = '8ed';
UPDATE tcg_set SET ck_name = 'Scourge' WHERE tcg = 'mtg' AND code = 'scg';
UPDATE tcg_set SET ck_name = 'Legions' WHERE tcg = 'mtg' AND code = 'lgn';
UPDATE tcg_set SET ck_name = 'Onslaught' WHERE tcg = 'mtg' AND code = 'ons';
UPDATE tcg_set SET ck_name = 'Judgment' WHERE tcg = 'mtg' AND code = 'jud';
UPDATE tcg_set SET ck_name = 'Torment' WHERE tcg = 'mtg' AND code = 'tor';
UPDATE tcg_set SET ck_name = 'Odyssey' WHERE tcg = 'mtg' AND code = 'ody';
UPDATE tcg_set SET ck_name = 'Apocalypse' WHERE tcg = 'mtg' AND code = 'apc';
UPDATE tcg_set SET ck_name = '7th Edition' WHERE tcg = 'mtg' AND code = '7ed';
UPDATE tcg_set SET ck_name = 'Planeshift' WHERE tcg = 'mtg' AND code = 'pls';
UPDATE tcg_set SET ck_name = 'Invasion' WHERE tcg = 'mtg' AND code = 'inv';
UPDATE tcg_set SET ck_name = 'Prophecy' WHERE tcg = 'mtg' AND code = 'pcy';
UPDATE tcg_set SET ck_name = 'Starter 2000' WHERE tcg = 'mtg' AND code = 's00';
UPDATE tcg_set SET ck_name = 'Nemesis' WHERE tcg = 'mtg' AND code = 'nem';
UPDATE tcg_set SET ck_name = 'Mercadian Masques' WHERE tcg = 'mtg' AND code = 'mmq';
UPDATE tcg_set SET ck_name = 'Starter 1999' WHERE tcg = 'mtg' AND code = 's99';
UPDATE tcg_set SET ck_name = 'Urza''s Destiny' WHERE tcg = 'mtg' AND code = 'uds';
UPDATE tcg_set SET ck_name = 'Urza''s Legacy' WHERE tcg = 'mtg' AND code = 'ulg';
UPDATE tcg_set SET ck_name = 'Anthologies' WHERE tcg = 'mtg' AND code = 'ath';
UPDATE tcg_set SET ck_name = 'Urza''s Saga' WHERE tcg = 'mtg' AND code = 'usg';
UPDATE tcg_set SET ck_name = 'Unglued' WHERE tcg = 'mtg' AND code = 'ugl';
UPDATE tcg_set SET ck_name = 'Exodus' WHERE tcg = 'mtg' AND code = 'exo';
UPDATE tcg_set SET ck_name = 'Stronghold' WHERE tcg = 'mtg' AND code = 'sth';
UPDATE tcg_set SET ck_name = 'Tempest' WHERE tcg = 'mtg' AND code = 'tmp';
UPDATE tcg_set SET ck_name = 'Weatherlight' WHERE tcg = 'mtg' AND code = 'wth';
UPDATE tcg_set SET ck_name = 'Portal' WHERE tcg = 'mtg' AND code = 'por';
UPDATE tcg_set SET ck_name = '5th Edition' WHERE tcg = 'mtg' AND code = '5ed';
UPDATE tcg_set SET ck_name = 'Visions' WHERE tcg = 'mtg' AND code = 'vis';
UPDATE tcg_set SET ck_name = 'Mirage' WHERE tcg = 'mtg' AND code = 'mir';
UPDATE tcg_set SET ck_name = 'Alliances' WHERE tcg = 'mtg' AND code = 'all';
UPDATE tcg_set SET ck_name = 'Homelands' WHERE tcg = 'mtg' AND code = 'hml';
UPDATE tcg_set SET ck_name = 'Chronicles' WHERE tcg = 'mtg' AND code = 'chr';
UPDATE tcg_set SET ck_name = 'Ice Age' WHERE tcg = 'mtg' AND code = 'ice';
UPDATE tcg_set SET ck_name = '4th Edition' WHERE tcg = 'mtg' AND code = '4ed';
UPDATE tcg_set SET ck_name = 'Fallen Empires' WHERE tcg = 'mtg' AND code = 'fem';
UPDATE tcg_set SET ck_name = 'The Dark' WHERE tcg = 'mtg' AND code = 'drk';
UPDATE tcg_set SET ck_name = 'Legends' WHERE tcg = 'mtg' AND code = 'leg';
UPDATE tcg_set SET ck_name = '3rd Edition' WHERE tcg = 'mtg' AND code = '3ed';
UPDATE tcg_set SET ck_name = 'Antiquities' WHERE tcg = 'mtg' AND code = 'atq';
UPDATE tcg_set SET ck_name = 'Arabian Nights' WHERE tcg = 'mtg' AND code = 'arn';
UPDATE tcg_set SET ck_name = 'Unlimited' WHERE tcg = 'mtg' AND code = '2ed';
UPDATE tcg_set SET ck_name = 'Beta' WHERE tcg = 'mtg' AND code = 'leb';
UPDATE tcg_set SET ck_name = 'Alpha' WHERE tcg = 'mtg' AND code = 'lea';
COMMIT;
