-- Deck Card Table
CREATE TABLE IF NOT EXISTS deck_card (
  id                UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id        UUID REFERENCES product(id) ON DELETE CASCADE,
  name              TEXT NOT NULL,
  set_code          TEXT,
  set_name          TEXT,
  collector_number  TEXT,
  rarity            TEXT,
  quantity          INTEGER NOT NULL DEFAULT 1,
  language          TEXT NOT NULL DEFAULT 'en',
  type_line         TEXT,
  color_identity    TEXT,
  cmc               NUMERIC(5, 1),
  is_legendary      BOOLEAN NOT NULL DEFAULT false,
  is_historic       BOOLEAN NOT NULL DEFAULT false,
  is_land           BOOLEAN NOT NULL DEFAULT false,
  is_basic_land     BOOLEAN NOT NULL DEFAULT false,
  art_variation     TEXT,
  oracle_text       TEXT,
  artist            TEXT,
  border_color      TEXT,
  frame             TEXT,
  full_art          BOOLEAN NOT NULL DEFAULT false,
  textless          BOOLEAN NOT NULL DEFAULT false,
  scryfall_id       UUID,
  oracle_id         UUID,
  is_prepared       BOOLEAN NOT NULL DEFAULT false,
  frame_effects     JSONB,
  legalities        JSONB,
  promo_type        TEXT,
  image_url         TEXT,
  foil_treatment    TEXT NOT NULL DEFAULT 'non_foil',
  card_treatment    TEXT NOT NULL DEFAULT 'normal',
  created_at        TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_deck_card_product ON deck_card(product_id);
