-- Expand theme properties with specialized colors and interactive elements
ALTER TABLE theme ADD COLUMN IF NOT EXISTS status_dmg TEXT NOT NULL DEFAULT '#455a64';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS bg_card TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS text_on_header TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS border_focus TEXT NOT NULL DEFAULT '#3b3127';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS btn_primary_bg TEXT NOT NULL DEFAULT '#1a1f2e';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS btn_primary_text TEXT NOT NULL DEFAULT '#ffffff';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS btn_secondary_bg TEXT NOT NULL DEFAULT 'transparent';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS btn_secondary_text TEXT NOT NULL DEFAULT '#3b3127';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS checkbox_border TEXT NOT NULL DEFAULT '#8b795c';
ALTER TABLE theme ADD COLUMN IF NOT EXISTS checkbox_checked TEXT NOT NULL DEFAULT '#d4af37';
